# Generated by Django 4.0.1 on 2022-01-06 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='updated_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 21, 2, 24, 666904)),
        ),
    ]
