# Generated by Django 4.0.1 on 2022-01-06 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_updated_date_alter_video_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 21, 44, 29, 505926)),
        ),
    ]
