# Generated by Django 4.0.1 on 2022-01-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_admin_user_country_user_email_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
